### ISSUE TITLE
Clarification on Fine-tuned Models for NSFW Removal in SD

### ISSUE THREAD

**Issue by Christina200** [JingWu321/EraseDiff#1]
Dear Authors,

Thanks for your amazing work!

In the models and training data you released for NSFW removal in SD, there are two different fine-tuned models:

- `diffusers-nsfw-wc-method_noxattn-Ksteps_2-lambdabome_1.0-lr_1e-05-step160.pt`

- `diffusers-nsfw-pm-method_noxattn-Ksteps_2-lambdabome_1.0-lr_1e-05-step160.pt`

Could you please clarify the difference between these two models? Additionally, are both models fine-tuned based on the NSFWData released in the same directory?

Thank you for your assistance!

**Comment by JingWu321** [comment]
> Dear Authors,
> 
> Thanks for your amazing work!
> 
> In the models and training data you released for NSFW removal in SD, there are two different fine-tuned models:
> 
> * `diffusers-nsfw-wc-method_noxattn-Ksteps_2-lambdabome_1.0-lr_1e-05-step160.pt`
> * `diffusers-nsfw-pm-method_noxattn-Ksteps_2-lambdabome_1.0-lr_1e-05-step160.pt`
> 
> Could you please clarify the difference between these two models? Additionally, are both models fine-tuned based on the NSFWData released in the same directory?
> 
> Thank you for your assistance!

**Comment by JingWu321** [comment]
> Dear Authors,
> 
> Thanks for your amazing work!
> 
> In the models and training data you released for NSFW removal in SD, there are two different fine-tuned models:
> 
> * `diffusers-nsfw-wc-method_noxattn-Ksteps_2-lambdabome_1.0-lr_1e-05-step160.pt`
> * `diffusers-nsfw-pm-method_noxattn-Ksteps_2-lambdabome_1.0-lr_1e-05-step160.pt`
> 
> Could you please clarify the difference between these two models? Additionally, are both models fine-tuned based on the NSFWData released in the same directory?
> 
> Thank you for your assistance!

**Comment by JingWu321** [comment]
> Dear Authors,
> 
> Thanks for your amazing work!
> 
> In the models and training data you released for NSFW removal in SD, there are two different fine-tuned models:
> 
> * `diffusers-nsfw-wc-method_noxattn-Ksteps_2-lambdabome_1.0-lr_1e-05-step160.pt`
> * `diffusers-nsfw-pm-method_noxattn-Ksteps_2-lambdabome_1.0-lr_1e-05-step160.pt`
> 
> Could you please clarify the difference between these two models? Additionally, are both models fine-tuned based on the NSFWData released in the same directory?
> 
> Thank you for your assistance!


Hi Christina,

Thanks for your interest in our work.

- xx-wc-xx: $\epsilon_f$ is replaced with $\epsilon_{\theta}(x_t|c_m)$ where $c_m$ is 'a person wearing clothes';

- xx-pm-xx: $\epsilon_f$ is replaced with $\epsilon_{\theta}(x_t|c_m)$ where $c_m$ is 'a photo of pokemon'.

Yes, both models were fine-tuned based on the NSFWData.

**Comment by Christina200** [comment]
Thanks for the clarification! 

Regarding the `step160` in the checkpoints, does it mean the models are trained for 160 epochs?

**Comment by JingWu321** [comment]
> Thanks for the clarification!
> 
> Regarding the `step160` in the checkpoints, does it mean the models are trained for 160 epochs?

This means that the models are trained for 160 steps, not the number of epochs. Sorry for the confusion caused.

**Comment by Christina200** [comment]
Question solved. Thanks!
